# Generated by Django 4.2.2 on 2023-06-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='therapist_photo',
            field=models.ImageField(blank=True, null=True, upload_to='therapist_images'),
        ),
    ]
