# Generated by Django 4.2.2 on 2023-06-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_records_therapist_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='therapist_id',
            new_name='therapist',
        ),
        migrations.RemoveField(
            model_name='records',
            name='therapist_photo',
        ),
    ]
