# Generated by Django 4.2.2 on 2023-07-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_clients_user_therapist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='therapists_images'),
        ),
    ]
