# Generated by Django 4.2.2 on 2023-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_therapist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
