# Generated by Django 4.2.2 on 2023-07-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_records_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
