# Generated by Django 4.2.2 on 2023-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_therapist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
