# Generated by Django 4.2.2 on 2023-07-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_therapist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_images'),
        ),
    ]
