# Generated by Django 4.2.2 on 2023-07-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_clients_photo_alter_therapist_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='password',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='password',
        ),
    ]
